---

# add the following apt install task to uninstall tasks otherwise the removal tasks fail
# Failed to find required executable gpg in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- name: Ensure gpg and apt-transport-https are present on the system
  ansible.builtin.apt:
   name:
    - gnupg
    - apt-transport-https
   state: present
   update_cache: yes

- name: Remove Microsoft's Apt signing key
  ansible.builtin.apt_key:
   url: https://packages.microsoft.com/keys/microsoft.asc
   state: "{{ vscode_installed_state }}"

- name: Remove microsoft apt repo for vscode
  ansible.builtin.apt_repository:
   repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
   state: "{{ vscode_installed_state }}"
   filename: "{{ vscode_apt_file_name }}"

- name: Remove vscode and update cache
  ansible.builtin.apt:
   name: "{{ vscode_package_name }}"
   state: "{{ vscode_installed_state }}"
