---

- name: Ensure gpg and apt-transport-https are present on the system
  apt:
   name:
    - gnupg
    - apt-transport-https
   state: present
   update_cache: yes

- name: Add Microsoft's Apt signing key
  apt_key:
   url: https://packages.microsoft.com/keys/microsoft.asc
   state: "{{ vscode_installed_state }}"

- name: Add microsoft apt repo for vscode
  apt_repository:
   repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
   state: "{{ vscode_installed_state }}"
   filename: "{{ vscode_apt_file_name }}"

- name: Add vscode and update cache
  apt:
   name: "{{ vscode_package_name }}"
   # code-insiders for beta?
   state: "{{ vscode_installed_state }}"

- name: Remove gnome-keyring
  # makes chromium way too annoying to use
  apt:
   name: gnome-keyring
   state: absent
   autoremove: yes
