---

- name: Ensure gpg and apt-transport-https is present on the system
  apt:
   name:
     - gnupg
     - apt-transport-https
   state: present
   update_cache: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add microsoft apt repo for vscode
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode

- name: Add vscode and update cache
  apt:
    name: code
    #code-insiders for beta?
    state: present

- name: Remove gnome-keyring
# makes chromium way too annoying to use
  apt:
    name: gnome-keyring
    state: absent
    autoremove: yes


