---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:

  - name: instance
    image: "${MOLECULE_DISTRO:-debian:9}"
    pull: yes
    groups:
      - vscode

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      vscode:
        user: qwe
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
