---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:

  - name: instance
    image: debian:9
    pull: yes
    groups:
     - vscode

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      vscode:
        user: qwe
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
